version: "3.9"
services:
  app:
    build: .
    image: "kpi-dashboard"
    container_name: "kpi-dashboard"
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: admin
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      APP_SECRET_KEY: dev
      FLASK_DEBUG: true
    ports:
      - "4567:4567"
    networks:
      - kpi-dashboard

  postgres:
    image: postgres:14-alpine
    container_name: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=admin
    networks:
      - kpi-dashboard

  # grafana:
  #   build:
  #     dockerfile: ./grafana/Dockerfile
  #     context: ./
  #   container_name: grafana
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - kpi-dashboard

networks:
  kpi-dashboard:
