version: "3.9"
services:
  app:
    build: .
    image: "kpi-dashboard"
    container_name: "kpi-dashboard"
    environment:
      KPI_DASHBOARD_URL: "http://127.0.0.1:4567"
      KPI_DASHBOARD_API_KEY: "test"
      AUTH_ENABLED: false
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: admin
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      APP_SECRET_KEY: dev
      FLASK_DEBUG: true
      API_KEY: test
    ports:
      - "4567:4567"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    networks:
      - kpi-dashboard

  postgres:
    image: postgres:14-alpine
    container_name: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kpi-dashboard

networks:
  kpi-dashboard:
