name: Auto Approve PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'data/production/support_request_stats.csv'

permissions:
  pull-requests: write
  contents: read

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'

    steps:
      - name: Auto approve PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
