name: 💰 Fetch GHA Cost Per Repository

on:
  pull_request:
  workflow_dispatch:

jobs:
  pat-token-report:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token to access Operations Engineering MOJ PAT App
        id: generate-token-moj
        uses: actions/create-github-app-token@ad38cffc07bac6e3857755914c4c88bfd2db4da4 # v1.10.2
        with:
          app-id: ${{ secrets.OE_MOJ_PAT_APP_ID }}
          private-key: ${{ secrets.OE_MOJ_PAT_APP_PRIVATE_KEY }}
      - name: Generate a token to access Operations Engineering AS PAT App
        id: generate-token-as
        uses: actions/create-github-app-token@ad38cffc07bac6e3857755914c4c88bfd2db4da4 # v1.10.2
        with:
          app-id: ${{ secrets.OE_AS_PAT_APP_ID }}
          private-key: ${{ secrets.OE_AS_PAT_APP_PRIVATE_KEY }}
          owner: moj-analytical-services
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: "3.11"
          cache: "pipenv"
      - name: Install Pipenv
        run: |
          pip install pipenv
          pipenv install
      - run: pipenv run python3 -m fetcher.bin.fetch_gha_min_cost
        env:
          GH_APP_MOJ_TOKEN: ${{ steps.generate-token-moj.outputs.token }}
          GH_APP_AS_TOKEN: ${{ steps.generate-token-as.outputs.token }}
          ADMIN_SLACK_TOKEN: ${{ secrets.ADMIN_SEND_TO_SLACK }}

      - name: Report failure to Slack
        if: ${{ always() && github.ref == 'refs/heads/main' }}
        uses: ravsamhq/notify-slack-action@472601e839b758e36c455b5d3e5e1a217d4807bd # 2.5.0
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "Failed GitHub Action Run"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}