name: 📈 Fetch GitHub Repositories Metadata

on:
  schedule:
     - cron: "0 1 * * 0"
  workflow_dispatch:

jobs:
  low-quota-threshold:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: "3.11"
          cache: "pipenv"
      - name: Install Pipenv
        run: |
          pip install pipenv
          pipenv install
      - run: pipenv run python3 -m fetcher.bin.fetch_gh_repos_metadata
        env: 
          GH_TOKEN: ${{ secrets.ENTERPRISE_BILLING_TOKEN_FROM_TONY }}
          KPI_DASHBOARD_URL: ${{ secrets.KPI_DASHBOARD_URL_PROD }}
          KPI_DASHBOARD_API_KEY: ${{ secrets.KPI_DASHBOARD_API_KEY_PROD }}
      - name: Report failure to Slack
        if: always()
        uses: ravsamhq/notify-slack-action@472601e839b758e36c455b5d3e5e1a217d4807bd # 2.5.0
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "Failed to fetch github actions quota"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}