name: Unit Tests

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Pipenv  
        run: |
          pip3 install --user pipenv
	        pipenv install
      - name: Run Unit Tests 
        run: pipenv run coverage run -m pytest fetcher/tests/ -v